const tasks = {
    "Lunes": [
        { task: "Minoxidil - Saw Palmeto", startHour: '6:30' , duration: 5 }, 
        { task: "Orden", startHour: '6:35' ,duration: 10 },  
        { task: "Ejercicio", startHour: '6:45', duration: 85 }, 
        { task: "Higiene - Ducha fria ", startHour: '8:00', duration: 30 },  
        { task: "Desayuno - Medium ", startHour: '8:30' ,duration: 30 },  
        { task: "Lumosity", startHour: '9:00', duration: 30 },  
        { task: "Research - Linkedin - Laborum ", startHour: '9:30', duration: 30 },  
        { task: "Cafe - galletas", startHour: '10:00', duration: 10 },  
        { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
        { task: "Granola", startHour: '12:00', duration: 10 },  
        { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
        { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
        { task: "BLOCK3 ()", startHour: '15:00', duration: 210 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:30', duration: 10 },  
        { task: "BLOCK4 ()", startHour: '18:40', duration: 80 },  
        { task: "Cocinar - Loza - Cena - Entretencion - HairTrack", startHour: '20:00', duration: 60 },  
        { task: "BLOCK5 ()", startHour: '21:01', duration: 90 },  
        { task: "Dormir", startHour: '22:30', duration: 0 },  

      ],
      "Martes": [
        { task: "Silicone Scalp Massager", startHour: '6:30' , duration: 5 }, 
        { task: "Minoxidile - Saw Palmeto", startHour: '6:35' , duration: 5 }, 
        { task: "Order ", startHour: '6:45' ,duration: 15 },  
        { task: "Lumosity", startHour: '7:00', duration: 30 }, 
        { task: "??", startHour: '7:30', duration: 30 }, 
        { task: "hygiene - Cold shower ", startHour: '8:00', duration: 30 },  
        { task: "Breakfast - Medium Reading", startHour: '8:30' ,duration: 30 },  
        { task: "??", startHour: '9:00', duration: 30 },  
        { task: "Research - Linkedin - Laborum ", startHour: '9:30', duration: 30 },  
        { task: "Coffe - Cookies", startHour: '10:00', duration: 10 },  
        { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
        { task: "Granola", startHour: '12:00', duration: 10 },  
        { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
        { task: "Lunch - tv - nap", startHour: '14:00', duration: 60 },  
        { task: "BLOCK3 ()", startHour: '15:00', duration: 60 },  
        { task: "Protein Bar", startHour: '16:00', duration: 1 },  
        { task: "BLOCK3 ()", startHour: '16:01', duration: 59 },  
        { task: "Minoxidile - Finasteride - Saw Palmetto", startHour: '18:30', duration: 10 },  
        { task: "BLOCK4 ()", startHour: '18:40', duration: 80 },  
        { task: "Cook - Wash Dishes - Dinnner - Fun - HairTrack", startHour: '20:00', duration: 60 },  
        { task: "BLOCK5 ()", startHour: '21:01', duration: 90 },  
        { task: "Sleep", startHour: '22:30', duration: 0 },  

      ],
      "Miercoles": [
        { task: "Minoxidil - Saw Palmeto", startHour: '6:30' , duration: 5 }, 
        { task: "Orden", startHour: '6:35' ,duration: 10 },  
        { task: "Ejercicio Fuerza", startHour: '6:45', duration: 85 }, 
        { task: "Higiene - Ducha fria ", startHour: '8:00', duration: 30 },  
        { task: "Desayuno - Medium ", startHour: '8:30' ,duration: 30 },  
        { task: "Lumosity", startHour: '9:00', duration: 30 },  
        { task: "Research - Linkedin - Laborum ", startHour: '9:30', duration: 30 },  
        { task: "Cafe - galletas", startHour: '10:00', duration: 10 },  
        { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
        { task: "Granola", startHour: '12:00', duration: 10 },  
        { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
        { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
        { task: "BLOCK3 ()", startHour: '15:00', duration: 210 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:30', duration: 10 },  
        { task: "BLOCK4 ()", startHour: '18:40', duration: 80 },  
        { task: "Cocinar - Loza - Cena - Entretencion - HairTrack", startHour: '20:00', duration: 60 },  
        { task: "BLOCK5 (Natacion)", startHour: '21:01', duration: 80 },  
        { task: "Dermastamp", startHour: '22:20', duration: 10 },  
        { task: "Dormir", startHour: '22:30', duration: 0 },  

      ],
      "Jueves": [
        { task: "Minoxidil  Saw-palmeto", startHour: '6:30' , duration: 10 }, 
        { task: "??", startHour: '6:41', duration: 19 }, 
        { task: "Desayuno Lectura noticias - Medium - Revisar correos", startHour: '7:01' ,duration: 29 },  
        { task: "Higiene - Orden - Cama", startHour: '7:31', duration: 29 },  
        { task: "??", startHour: '8:01', duration: 59 },  
        { task: "BLOCK", startHour: '9:01', duration: 179 },  
        { task: "Granola", startHour: '12:01', duration: 9 },  
        { task: "BLOCK", startHour: '12:11', duration: 109 },  
        { task: "almuerzo - video - siesta", startHour: '14:01', duration: 59 },  
        { task: "BLOCK", startHour: '15:01', duration: 209 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:31', duration: 9 },  
        { task: "BLOCK4 (Ejercicio)", startHour: '18:40', duration: 80 },  
        { task: "cocinar-lavar-cena-entretencion", startHour: '20:01', duration: 59 },  
        { task: "BLOCK", startHour: '21:01', duration: 89 },  
        { task: "Dermastamp", startHour: '22:21', duration: 9 }  
      ],
      "Viernes": [
        { task: "Minoxidil - Saw Palmeto", startHour: '6:30' , duration: 5 }, 
        { task: "Orden", startHour: '6:35' ,duration: 10 },  
        { task: "Ciclying", startHour: '6:45', duration: 85 }, 
        { task: "Higiene - Ducha fria ", startHour: '8:00', duration: 30 },  
        { task: "Desayuno - Medium ", startHour: '8:30' ,duration: 30 },  
        { task: "Lumosity", startHour: '9:00', duration: 30 },  
        { task: "Research - Linkedin - Laborum ", startHour: '9:30', duration: 30 },  
        { task: "Cafe - galletas", startHour: '10:00', duration: 10 },  
        { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
        { task: "Granola", startHour: '12:00', duration: 10 },  
        { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
        { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
        { task: "BLOCK3 ()", startHour: '15:00', duration: 210 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:30', duration: 10 },  
        { task: "BLOCK4 ()", startHour: '18:40', duration: 80 },  
        { task: "Cocinar - Loza - Cena - Entretencion - HairTrack", startHour: '20:00', duration: 60 },  
        { task: "BLOCK5 (Natacion)", startHour: '21:01', duration: 80 },  
        { task: "Dermastamp", startHour: '22:20', duration: 10 },  
        { task: "Dormir", startHour: '22:30', duration: 0 },  

      ],
  };

