  const tasks = {
    "Lunes": [
<<<<<<< HEAD
        { task: "Minoxidil  Saw-palmeto", startHour: '6:30' , duration: 5 }, 
        { task: "Ejercicio de fuerza", startHour: '6:36', duration: 23 }, 
        { task: "Desayuno Lectura noticias - Medium - Revisar correos", startHour: '7:01' ,duration: 29 },  
        { task: "Higiene - Ducha fria - Orden - Cama", startHour: '7:31', duration: 29 },  
        { task: "??", startHour: '8:01', duration: 59 },  
        { task: "BLOCK", startHour: '9:01', duration: 179 },  
        { task: "Granola y cafe", startHour: '12:01', duration: 9 },  
        { task: "BLOCK", startHour: '12:11', duration: 109 },  
        { task: "almuerzo - video - siesta", startHour: '14:01', duration: 59 },  
        { task: "BLOCK ()", startHour: '15:01', duration: 209 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:31', duration: 9 },  
        { task: "BLOCK", startHour: '18:41', duration: 79 },  
        { task: "cocinar-lavar-cena-entretencion", startHour: '20:01', duration: 59 },  
        { task: "BLOCK", startHour: '21:01', duration: 85 },  
        { task: "Ketoconazol", startHour: '22:26', duration: 4 } 
      ],
    "Martes": [
        { task: "Minoxidil  Saw-palmeto", startHour: '6:30' , duration: 10 }, 
        { task: "??", startHour: '6:41', duration: 19 }, 
        { task: "Desayuno Lectura noticias - Medium - Revisar correos", startHour: '7:01' ,duration: 29 },  
        { task: "Higiene - Orden - Cama", startHour: '7:31', duration: 29 },  
        { task: "??", startHour: '8:01', duration: 59 },  
        { task: "BLOCK", startHour: '9:01', duration: 179 },  
        { task: "Granola  y cafe", startHour: '12:01', duration: 9 },  
        { task: "BLOCK", startHour: '12:11', duration: 109 },  
        { task: "almuerzo - video - siesta", startHour: '14:01', duration: 59 },  
        { task: "BLOCK", startHour: '15:01', duration: 209 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:31', duration: 9 },  
        { task: "BLOCK", startHour: '18:41', duration: 79 },  
        { task: "cocinar-lavar-cena-entretencion", startHour: '20:01', duration: 59 },  
        { task: "BLOCK", startHour: '21:01', duration: 89 },  
        { task: "Dermastamp", startHour: '22:21', duration: 9 }  ,
        { task: "Ketoconazol", startHour: '22:30', duration: 4 },  

      ],
      "Miercoles": [
        { task: "Minoxidil  Saw-palmeto", startHour: '6:30' , duration: 5 }, 
        { task: "Ejercicio de fuerza", startHour: '6:36', duration: 23 }, 
        { task: "Desayuno Lectura noticias - Medium - Revisar correos", startHour: '7:01' ,duration: 29 },  
        { task: "Higiene - Ducha fria - Orden - Cama", startHour: '7:31', duration: 29 },  
        { task: "??", startHour: '8:01', duration: 59 },  
        { task: "BLOCK", startHour: '9:01', duration: 179 },  
        { task: "Granola y cafe", startHour: '12:01', duration: 9 },  
        { task: "BLOCK", startHour: '12:11', duration: 109 },  
        { task: "almuerzo - video - siesta", startHour: '14:01', duration: 59 },  
        { task: "BLOCK", startHour: '15:01', duration: 209 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:31', duration: 9 },  
        { task: "BLOCK", startHour: '18:41', duration: 79 },  
        { task: "cocinar-lavar-cena-entretencion", startHour: '20:01', duration: 59 },  
        { task: "BLOCK", startHour: '21:01', duration: 89 },  
        { task: "Ketoconazol", startHour: '22:30', duration: 4 },  

      ],
      "Jueves": [
        { task: "Minoxidil  Saw-palmeto", startHour: '6:30' , duration: 10 }, 
        { task: "??", startHour: '6:41', duration: 19 }, 
        { task: "Desayuno Lectura noticias - Medium - Revisar correos", startHour: '7:01' ,duration: 29 },  
        { task: "Higiene - Orden - Cama", startHour: '7:31', duration: 29 },  
        { task: "??", startHour: '8:01', duration: 59 },  
        { task: "BLOCK1 ()", startHour: '9:01', duration: 179 },  
        { task: "Granola y cafe", startHour: '12:01', duration: 9 },  
        { task: "BLOCK2 ()", startHour: '12:11', duration: 109 },  
        { task: "almuerzo - video - siesta", startHour: '14:01', duration: 59 },  
        { task: "BLOCK3 ()", startHour: '15:01', duration: 209 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:31', duration: 9 },  
        { task: "BLOCK4 ()", startHour: '18:41', duration: 79 },  
        { task: "cocinar-lavar-cena-entretencion", startHour: '20:01', duration: 59 },  
        { task: "BLOCK5 ()", startHour: '21:01', duration: 89 },  
        { task: "Dermastamp", startHour: '22:21', duration: 9 }  ,
        { task: "Ketoconazol", startHour: '22:30', duration: 4 },  
    ],
    
      "Viernes": [
        { task: "Minoxidil  Saw-palmeto", startHour: '6:30' , duration: 5 }, 
        { task: "Ejercicio de fuerza", startHour: '6:36', duration: 23 }, 
        { task: "Desayuno Lectura noticias - Medium - Revisar correos", startHour: '7:01' ,duration: 29 },  
        { task: "Higiene - Ducha fria - Orden - Cama", startHour: '7:31', duration: 29 },  
        { task: "??", startHour: '8:01', duration: 59 },  
        { task: "BLOCK", startHour: '9:01', duration: 179 },  
        { task: "Granola y cafe", startHour: '12:01', duration: 9 },  
        { task: "BLOCK", startHour: '12:11', duration: 109 },  
        { task: "almuerzo - video - siesta", startHour: '14:01', duration: 59 },  
        { task: "BLOCK", startHour: '15:01', duration: 209 },  
        { task: "Minoxidil - Finasteride - Saw Palmetto", startHour: '18:31', duration: 9 },  
        { task: "BLOCK", startHour: '18:41', duration: 79 },  
        { task: "cocinar-lavar-cena-entretencion", startHour: '20:01', duration: 59 },  
        { task: "BLOCK", startHour: '21:01', duration: 89 },  
        { task: "Ketoconazol", startHour: '22:30', duration: 4 },  

      ],
  };

=======
     { task: "Stretching", startHour: '7:00' , duration: 30 }, 
     { task: "Shower", startHour: '7:30' ,duration: 10 },  
     { task: "Order", startHour: '7:40', duration: 20 }, 
     { task: "Lumosity", startHour: '8:00', duration: 15 },  
     { task: "Breakfast", startHour: '8:15' ,duration: 15 },  
     { task: "Medium - Mails", startHour: '8:30', duration: 30 },  
     { task: "Block 1", startHour: '9:00', duration: 60 },  
     { task: "Coffe - Regaloteca ", startHour: '10:00', duration: 60 }, 
     { task: "Block 2 ", startHour: '11:00', duration: 60 },  
     { task: "Granola", startHour: '12:00', duration: 10 },  
     { task: "Block 3 ", startHour: '12:10', duration: 110 },  
     { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
     { task: "Block 4 -  protein bar", startHour: '15:00', duration: 210 },  
     { task: "Exercise", startHour: '18:30', duration: 90 },  
     { task: "Cook - Dishes - Dinner - Fun", startHour: '20:00', duration: 60 },  
     { task: "Minoxi - Finas- Vitamin", startHour: '21:00', duration: 10 },  
     { task: "Block 5 ", startHour: '21:10', duration: 70 },  
   ],
     "Martes": [
    { task: "Stretching", startHour: '7:00' , duration: 30 }, 
     { task: "Shower", startHour: '7:30' ,duration: 10 },  
     { task: "Order", startHour: '7:40', duration: 20 }, 
     { task: "Lumosity", startHour: '8:00', duration: 15 },  
     { task: "Breakfast", startHour: '8:15' ,duration: 15 },  
     { task: "Medium - Mails", startHour: '8:30', duration: 30 },  
     { task: "Block 1", startHour: '9:00', duration: 60 },  
     { task: "Coffe - Regaloteca ", startHour: '10:00', duration: 60 }, 
     { task: "Block 2 ", startHour: '11:00', duration: 60 },  
     { task: "Granola", startHour: '12:00', duration: 10 },  
     { task: "Block 3 ", startHour: '12:10', duration: 110 },  
     { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
     { task: "Block 4 -  protein bar", startHour: '15:00', duration: 210 },  
     { task: "??", startHour: '18:30', duration: 90 },  
     { task: "Cook - Dishes - Dinner - Fun", startHour: '20:00', duration: 60 },  
     { task: "Minoxi - Finas- Vitamin", startHour: '21:00', duration: 10 },  
     { task: "Block 5 ", startHour: '21:10', duration: 70 },  
   ],
     "Miércoles": [
    { task: "Stretching", startHour: '7:00' , duration: 30 }, 
     { task: "Shower", startHour: '7:30' ,duration: 10 },  
     { task: "Order", startHour: '7:40', duration: 20 }, 
     { task: "Lumosity", startHour: '8:00', duration: 15 },  
     { task: "Breakfast", startHour: '8:15' ,duration: 15 },  
     { task: "Medium - Mails", startHour: '8:30', duration: 30 },  
     { task: "Block 1", startHour: '9:00', duration: 60 },  
     { task: "Coffe - Regaloteca ", startHour: '10:00', duration: 60 }, 
     { task: "Block 2 ", startHour: '11:00', duration: 60 },  
     { task: "Granola", startHour: '12:00', duration: 10 },  
     { task: "Block 3 ", startHour: '12:10', duration: 110 },  
     { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
     { task: "Block 4 -  protein bar", startHour: '15:00', duration: 210 },  
     { task: "Exercise", startHour: '18:30', duration: 90 },  
     { task: "Cook - Dishes - Dinner - Fun", startHour: '20:00', duration: 60 },  
     { task: "Finas- Vitamin", startHour: '21:00', duration: 5 },  
     { task: "Dermastamp", startHour: '21:05', duration: 5 },  
     { task: "Block 5 ", startHour: '21:10', duration: 70 },  
   ],
    "Jueves": [
    { task: "Stretching", startHour: '7:00' , duration: 30 }, 
     { task: "Shower", startHour: '7:30' ,duration: 10 },  
     { task: "Order", startHour: '7:40', duration: 20 }, 
     { task: "Lumosity", startHour: '8:00', duration: 15 },  
     { task: "Breakfast", startHour: '8:15' ,duration: 15 },  
     { task: "Medium - Mails", startHour: '8:30', duration: 30 },  
     { task: "Block 1", startHour: '9:00', duration: 60 },  
     { task: "Coffe - Regaloteca ", startHour: '10:00', duration: 60 }, 
     { task: "Block 2 ", startHour: '11:00', duration: 60 },  
     { task: "Granola", startHour: '12:00', duration: 10 },  
     { task: "Block 3 ", startHour: '12:10', duration: 110 },  
     { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
     { task: "Block 4 -  protein bar", startHour: '15:00', duration: 210 },  
     { task: "Exercise", startHour: '18:30', duration: 90 },  
     { task: "Cook - Dishes - Dinner - Fun", startHour: '20:00', duration: 60 },  
     { task: "Minoxi - Finas- Vitamin", startHour: '21:00', duration: 10 },  
     { task: "Block 5 ", startHour: '21:10', duration: 80 }, 
     { task: "Ketoconazole", startHour: '22:30', duration: 10 },  
   ],
    "Viernes": [
     { task: "Stretching", startHour: '7:00' , duration: 30 }, 
     { task: "Shower", startHour: '7:30' ,duration: 10 },  
     { task: "Order", startHour: '7:40', duration: 20 }, 
     { task: "Lumosity", startHour: '8:00', duration: 15 },  
     { task: "Breakfast", startHour: '8:15' ,duration: 15 },  
     { task: "Medium - Mails", startHour: '8:30', duration: 30 },  
     { task: "Research Jobs - New Technologies", startHour: '9:00', duration: 60 },  
     { task: "Coffe - Regaloteca ", startHour: '10:00', duration: 60 }, 
     { task: "Block 2 ", startHour: '11:00', duration: 60 },  
     { task: "Granola", startHour: '12:00', duration: 10 },  
     { task: "Block 3 ", startHour: '12:10', duration: 110 },  
     { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
     { task: "Block 4  -  protein bar", startHour: '15:00', duration: 210 }, 
   ],
};
>>>>>>> b5dc9449ada9617bd124aa2f3ebe0eaca523ad08
