const tasks = {
    "Lunes": [
        { task: "Silicone Scalp Massager", startHour: '6:30' , duration: 5 }, 
        { task: "Minoxidile - Saw Palmeto", startHour: '6:35' , duration: 5 }, 
        { task: "Order", startHour: '6:40' ,duration: 10 },  
        { task: "Running", startHour: '6:50', duration: 70 }, 
        { task: "Hygiene - Cold Shower ", startHour: '8:00', duration: 30 },  
        { task: "Breakfast - Medium Reading - News", startHour: '8:30' ,duration: 30 },  
        { task: "Lumosity", startHour: '9:00', duration: 30 },  
        { task: "Research - Linkedin - Laborum - Mails ", startHour: '9:30', duration: 30 },  
        { task: "Coffe - Cookies", startHour: '10:00', duration: 10 },  
        { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
        { task: "Granola", startHour: '12:00', duration: 10 },  
        { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
        { task: "Lunch - Fun - Nap", startHour: '14:00', duration: 60 },  
        { task: "BLOCK3 () -  Protein bar", startHour: '15:00', duration: 210 },  
        { task: "Minoxidile - Finasteride - Saw Palmetto - Iron Intake", startHour: '18:30', duration: 10 },  
        { task: "BLOCK4 ()", startHour: '18:40', duration: 80 },  
        { task: "Cook - Wash Dishes - Dinner - FUn - HairTrack", startHour: '20:00', duration: 60 },  
        { task: "BLOCK5 ()", startHour: '21:01', duration: 90 },  
        { task: "Ketoconazole", startHour: '22:25', duration: 5 },          
        { task: "Sleep", startHour: '22:30', duration: 0 },  
      ],
      "Martes": [
        { task: "Silicone Scalp Massage", startHour: '7:40' ,duration: 5 },  
        { task: "Minoxidile - Saw Palmeto ", startHour: '7:45', duration: 5 }, 
        { task: "Order", startHour: '7:50', duration: 10 }, 
        { task: "Lumosity", startHour: '8:00', duration: 30 },  
        { task: "Hygiene - Cold shower", startHour: '8:30' ,duration: 30 },  
        { task: "Breakfast - Medium Reading -News", startHour: '9:00', duration: 30 },  
        { task: "Research - LIndedin - Laborum Emails ", startHour: '9:30', duration: 30 },  
        { task: "Coffe - Cookies", startHour: '10:00', duration: 10 },  
        { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
        { task: "Granola", startHour: '12:00', duration: 10 },  
        { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
        { task: "Lunch - Tv - Nap", startHour: '14:00', duration: 60 },  
        { task: "BLOCK3 () -  Protein bar", startHour: '15:00', duration: 210 },  
        { task: "Minoxidile - Finasteride - Saw Palmetto - Maltofer", startHour: '18:30', duration: 10 },  
        { task: "Cook - Wash Dishes - Dinnner - Fun - HairTrack", startHour: '18:40', duration: 60 },  
        { task: "Study", startHour: '19:40', duration: 120 },  
        { task: "BLOCK4 ()", startHour: '21:40', duration: 45 },  
        { task: "Ketoconazole", startHour: '22:25', duration: 5 },    
        { task: "Sleep", startHour: '22:30', duration: 0 },  
      ],
      "Miercoles": [
          { task: "Silicone Scalp Massager", startHour: '6:30' , duration: 5 }, 
          { task: "Minoxidile - Saw Palmeto", startHour: '6:35' , duration: 5 }, 
          { task: "Order", startHour: '6:40' ,duration: 10 },  
          { task: "??", startHour: '6:50', duration: 70 }, 
          { task: "Hygiene - Cold Shower ", startHour: '8:00', duration: 30 },  
          { task: "Breakfast - Medium Reading", startHour: '8:30' ,duration: 30 },  
          { task: "Lumosity", startHour: '9:00', duration: 30 },  
          { task: "Research - Linkedin - Laborum - Mails ", startHour: '9:30', duration: 30 },  
          { task: "Coffe - Cookies", startHour: '10:00', duration: 10 },  
          { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
          { task: "Granola", startHour: '12:00', duration: 10 },  
          { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
          { task: "Lunch - Fun - Nap", startHour: '14:00', duration: 60 },  
          { task: "BLOCK3 () -  Protein bar", startHour: '15:00', duration: 210 },  
          { task: "Minoxidile - Finasteride - Saw Palmetto - Iron Intake", startHour: '18:30', duration: 10 },  
          { task: "BLOCK4 ()", startHour: '18:40', duration: 80 },  
          { task: "Cook - Wash Dishes - Dinner - FUn - HairTrack", startHour: '20:00', duration: 60 },  
          { task: "Swimming", startHour: '21:01', duration: 90 },  
          { task: "Ketoconazole", startHour: '22:20', duration: 5 },  
          { task: "Dermastamp", startHour: '22:25', duration: 5 },
          { task: "Sleep", startHour: '22:30', duration: 0 },  
  
        ],
        "Jueves": [
          { task: "Silicone Scalp Massage", startHour: '7:40' ,duration: 5 },  
          { task: "Minoxidile - Saw Palmeto ", startHour: '7:45', duration: 5 }, 
          { task: "Order", startHour: '7:50', duration: 10 }, 
          { task: "Lumosity", startHour: '8:00', duration: 30 },  
          { task: "Hygiene - Cold shower", startHour: '8:30' ,duration: 30 },  
          { task: "Breakfast - Medium Reading -News", startHour: '9:00', duration: 30 },  
          { task: "Research - LIndedin - Laborum Emails ", startHour: '9:30', duration: 30 },  
          { task: "Coffe - Cookies", startHour: '10:00', duration: 10 },  
          { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
          { task: "Granola", startHour: '12:00', duration: 10 },  
          { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
          { task: "Lunch - Tv - Nap", startHour: '14:00', duration: 60 },  
          { task: "BLOCK3 () -  Protein bar", startHour: '15:00', duration: 210 },  
          { task: "Minoxidile - Finasteride - Saw Palmetto - Maltofer", startHour: '18:30', duration: 10 },  
          { task: "Cook - Wash Dishes - Dinnner - Fun - HairTrack", startHour: '18:40', duration: 60 },  
          { task: "Study", startHour: '19:40', duration: 120 },  
          { task: "BLOCK4 ()", startHour: '21:40', duration: 45 },  
          { task: "Ketoconazole", startHour: '22:25', duration: 5 },    
          { task: "Sleep", startHour: '22:30', duration: 0 },  
        ],
      "Viernes": [
        { task: "Minoxidil - Saw Palmeto", startHour: '6:30' , duration: 5 }, 
        { task: "Orden", startHour: '6:35' ,duration: 10 },  
        { task: "Ciclying", startHour: '6:45', duration: 85 }, 
        { task: "Higiene - Ducha fria ", startHour: '8:00', duration: 30 },  
        { task: "Desayuno - Medium ", startHour: '8:30' ,duration: 30 },  
        { task: "Lumosity", startHour: '9:00', duration: 30 },  
        { task: "Research - Linkedin - Laborum ", startHour: '9:30', duration: 30 },  
        { task: "Cafe - galletas", startHour: '10:00', duration: 10 },  
        { task: "BLOCK1 ()", startHour: '10:10', duration: 110 },  
        { task: "Granola", startHour: '12:00', duration: 10 },  
        { task: "BLOCK2 ()", startHour: '12:10', duration: 110 },  
        { task: "Almuerzo - Entretencion - siesta", startHour: '14:00', duration: 60 },  
        { task: "BLOCK3 () -  protein bar", startHour: '15:00', duration: 210 },  
        { task: "Minoxidile - Finasteride - Saw Palmetto - Maltofer", startHour: '18:30', duration: 10 },  
        { task: "BLOCK4 ()", startHour: '18:40', duration: 80 },  
        { task: "Cocinar - Loza - Cena - Entretencion - HairTrack", startHour: '20:00', duration: 60 },  
        { task: "BLOCK5 ()", startHour: '21:01', duration: 80 },  
        { task: "Dermastamp", startHour: '22:20', duration: 10 },  
        { task: "Ketoconazol", startHour: '22:25', duration: 5 },    
        { task: "Dormir", startHour: '22:30', duration: 0 },  

      ],
  };

